config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  #devise_for :users

  root 'homes#index'

  resources :homes
  resources :admins
  resources	:barcodes
  resources :user_groups
  resources :warehouse_statuses
  resources :warehouses do
    resources :warehouse_bins
  end
  
  resources :product_types  
  resources :users
  resources :delivery_orders
  resources :products

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/barcode.rb
class Barcode< ActiveRecord::Base

end

app/models/delivery_order.rb
class DeliveryOrder < ActiveRecord::Base
	self.establish_connection(
		adapter: "mysql2",
		encoding: "utf8",
		pool: 5,
		database: "wicommerces",
		username: "root",
		password: "",
		host: "localhost",
		socket: "/Applications/XAMPP/xamppfiles/var/mysql/mysql.sock"
	)
end

app/models/product.rb
class Product < ActiveRecord::Base	
	self.establish_connection(
		adapter: "mysql2",
		encoding: "utf8",
		pool: 5,
		database: "wicommerces",
		username: "root",
		password: "",
		host: "localhost",
		socket: "/Applications/XAMPP/xamppfiles/var/mysql/mysql.sock"
	)

	belongs_to :product_type	
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
	self.establish_connection(
		adapter: "mysql2",
		encoding: "utf8",
		pool: 5,
		database: "wicommerces",
		username: "root",
		password: "",
		host: "localhost",
		socket: "/Applications/XAMPP/xamppfiles/var/mysql/mysql.sock"
	)

	has_many :products, dependent: :restrict_with_exception
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :user_group
end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
	has_many :user
	belongs_to :warehouse_status
end

app/models/warehouse.rb
class Warehouse < ActiveRecord::Base
	has_many :warehouse_bins
end

app/models/warehouse_bin.rb
class WarehouseBin < ActiveRecord::Base
	belongs_to :warehouse
end

app/models/warehouse_status.rb
class WarehouseStatus < ActiveRecord::Base
	has_many :user_group
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_filter :authenticate_admin!
  before_action :set_admin, only: [:show, :edit, :update, :destroy]

  layout "admin"
  
  # GET /admins
  # GET /admins.json
  def index
	@admins = Admin.all
  end

  # GET /admins/1
  # GET /admins/1.json
  def show
  end

  # GET /admins/new
  def new
    @admin = Admin.new
  end

  # GET /admins/1/edit
  def edit
  end

  # POST /admins
  # POST /admins.json
  def create
    @admin = Admin.new(admin_params)

    respond_to do |format|
      if @admin.save
        format.html { redirect_to [:admin, @admin], notice: 'Barcode was successfully created.' }
        format.json { render :show, status: :created, location: @admin }
      else
        format.html { render :new }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admins/1
  # PATCH/PUT /admins/1.json
  def update
    respond_to do |format|
      if @admin.update(admin_params)
        format.html { redirect_to [:admin, @admin], notice: 'Barcode was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin }
      else
        format.html { render :edit }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/1
  # DELETE /admins/1.json
  def destroy
    @admin.destroy
    respond_to do |format|
     format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin
      @admin = Admin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_params
      params.require(:admin).permit(:username, :name, :password, :password_confrimation, :email)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	before_action :authenticate_admin!

	def index
		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_admin!
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  layout "admin"
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @user_groups = UserGroup.all
  end

  # GET /users/1/edit
  def edit
    @user_groups = UserGroup.all
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to [@user], notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to [@user], notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :name, :password, :password_confirmation, :email, :user_group_id, :user_group_id)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/delivery_orders_helper.rb
module DeliveryOrdersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/_form.html.erb
<%= form_for(@admin, html: {class: "form-horizontal"}) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if params[:action] == "new" %>
      <%= f.hidden_field :created_by, :value => current_admin.id %>
    <% else %>
      <%= f.hidden_field :updated_by, :value => current_admin.id %>
    <% end %>

  <div class="form-group">
    <label class="col-sm-3 control-label">
      Name
    </label>
    <div class="col-sm-7">
      <%= f.text_field :name, class: 'form-control', placeholder: 'Enter name ..' %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">
      Username
    </label>
    <div class="col-sm-7">
      <%= f.text_field :username, class: 'form-control', placeholder: 'Enter username ..' %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">
      Password
    </label>
    <div class="col-sm-7">
      <%= f.password_field :password, class: "form-control", placeholder: "Enter password .." %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">
      Confrim Password
    </label>
    <div class="col-sm-7">
      <%= f.password_field :password_confrimation, class: "form-control", placeholder: "Enter confrim password .." %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">
      Email
    </label>
    <div class="col-sm-7">
      <%= f.text_field :email, class: 'form-control', placeholder: 'Enter email ..' %>
    </div>
  </div>
  <button type="submit" class="btn btn-o btn-primary">
    Submit
  </button>
<% end %>

<%= content_for :css do %>
  
    <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
    <link href="/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/bootstrap-datepicker/bootstrap-datepicker3.standalone.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/bootstrap-timepicker/bootstrap-timepicker.min.css" rel="stylesheet" media="screen">
    <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
<% end %>

<%= content_for :js do %>
    
    <!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
    <script src="/vendor/ckeditor/ckeditor.js"></script>
    <script src="/vendor/ckeditor/adapters/jquery.js"></script>
    <script src="/vendor/jquery-validation/jquery.validate.min.js"></script>

    <script src="/vendor/maskedinput/jquery.maskedinput.min.js"></script>
    <script src="/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js"></script>
    <script src="/vendor/autosize/autosize.min.js"></script>
    <script src="/vendor/selectFx/classie.js"></script>
    <script src="/vendor/selectFx/selectFx.js"></script>
    <script src="/vendor/select2/select2.min.js"></script>
    <script src="/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <script src="/vendor/bootstrap-timepicker/bootstrap-timepicker.min.js"></script>
    <!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
  
    <!-- start: JavaScript Event Handlers for this page -->
    <script src="/assets/js/form-validation.js"></script>
    <script src="/assets/js/form-elements.js"></script>
    <script>
      jQuery(document).ready(function() {
        Main.init();
        FormValidator.init();
        FormElements.init();
      });
    </script>
<% end %>

app/views/admins/edit.html.erb
					<div class="wrap-content container" id="container">
						<!-- start: PAGE TITLE -->
						<section id="page-title">
							<div class="row">
								<div class="col-sm-8">
									<h1 class="mainTitle">Form Ubah Admin</h1>
									<span class="mainDescription">Form untuk ubah data Admin</span>
								</div>
								<ol class="breadcrumb">
									<li>
										<span>Admin Forms</span>
									</li>
									<li class="active">
										<span>Form Admin</span>
									</li>
								</ol>
							</div>
						</section>
						<!-- end: PAGE TITLE -->
						<!-- start: BASIC EXAMPLE -->
						<div class="container-fluid container-fullw bg-white">
							<div class="row">
								<div class="col-md-12">
									<div class="row">
										<div class="col-lg-8 col-md-12">
											<div class="panel panel-white">
												<div class="panel-heading">
													<h5 class="panel-title">Form Ubah</h5>
												</div>
												<div class="panel-body">
													<%= render "form" %>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>

							<div class="row">
			                    <div class="col-md-12 space20">
								<a href="/admins/<%= params[:id] %>" class="btn btn-green">
									Show <i class="fa fa-search-plus"></i>
								</a>
								<a href="/admins" class="btn btn-info">
									Back <i class="fa fa-reply"></i>
								</a>
			                    </div>
		                  	</div>
						</div>
						<!-- end: BASIC EXAMPLE -->
					</div>

app/views/admins/index.html.erb
          <div class="wrap-content container" id="container">
            <!-- start: PAGE TITLE -->
            <section id="page-title">
              <div class="row">
                <div class="col-sm-8">
                  <h1 class="mainTitle">ADMINS LIST</h1>
                  <span class="mainDescription">Halaman untuk menampilkan daftar admin</span>
                </div>
                <ol class="breadcrumb">
                  <li>
                    <span>Dashboard</span>
                  </li>
                  <li class="active">
                    <span>Admin List</span>
                  </li>
                </ol>
              </div>
            </section>
            <p id="notice"><%= notice %></p>
            <!-- end: PAGE TITLE -->
            <!-- start: DYNAMIC TABLE -->
            <div class="container-fluid container-fullw">
              <div class="row">
                <div class="col-md-12">
                  <h5 class="over-title margin-bottom-15">List of <span class="text-bold">Admin</span></h5>
                  <div class="row">
                    <div class="col-md-12 space20">
                      <a href="/admins/new" class="btn btn-green">
                        Add New <i class="fa fa-plus"></i>
                      </a>
                    </div>
                  </div>
               <!--     <div class="row">
                    <div class="col-md-12 space20">

                      <a href="/user_excels/new" class="btn btn-blue">
                        Import <i class="fa fa-plus"></i>
                      </a>
                      
                    </div>
                  </div> -->
                  <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover table-full-width dataTable no-footer" id="sample_1">
                      <thead>
                        <tr>
                          <th>Username</th>
                          <th>Email</th>
                          <th>Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @admins.each do |admin| %>
                          <tr>
                            <td><%= link_to admin.username, admin_path(admin) %></td>
                            <td><%= admin.email %></td>
                            <td>
                              <%= link_to edit_admin_path(admin) do %>
                                <i class="fa fa-edit"></i>
                              <% end %>

                              <%= link_to admin_path(admin), method: :delete, data: {confirm: "are you sure?"} do %>
                                <i class="fa fa-trash"></i>
                              <% end %>
                            </td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <%= content_for :css do %>
            <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
            <link href="/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
            <link href="/vendor/DataTables/css/DT_bootstrap.css" rel="stylesheet" media="screen">
            <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
          <% end %>

          <%= content_for :js do %>
            <script src="/vendor/select2/select2.min.js"></script>
            <script src="/vendor/DataTables/jquery.dataTables.min.js"></script>
            <!-- start: JavaScript Event Handlers for this page -->
            <script src="/assets/js/table-data.js"></script>
            <script>
              jQuery(document).ready(function() {
                Main.init();
                TableData.init();
              });
            </script>
            <!-- end: JavaScript Event Handlers for this page -->
          <% end %>

app/views/admins/new.html.erb
<div class="wrap-content container" id="container">
	<!-- start: PAGE TITLE -->
	<section id="page-title">
		<div class="row">
			<div class="col-sm-8">
				<h1 class="mainTitle">Form Tambah Admin</h1>
				<span class="mainDescription">Form untuk menambah data Admin yang baru</span>
			</div>
			<ol class="breadcrumb">
				<li>
					<span>Admin Forms</span>
				</li>
				<li class="active">
					<span>Form Admin</span>
				</li>
			</ol>
		</div>
	</section>
	<!-- end: PAGE TITLE -->
	<!-- start: BASIC EXAMPLE -->
	<div class="container-fluid container-fullw bg-white">
		<div class="row">
			<div class="col-md-12">
				<div class="row">
					<div class="col-lg-8 col-md-12">
						<div class="panel panel-white">
							<div class="panel-heading">
								<h5 class="panel-title">Form Tambah</h5>
							</div>
							<div class="panel-body">
								<%= render "form" %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
            <a href="/admins" class="btn btn-info">
              Back <i class="fa fa-reply"></i>
            </a>
      	</div>
	</div>
	<!-- end: BASIC EXAMPLE -->
</div>

app/views/admins/show.html.erb
  <div class="wrap-content container" id="container">
    <!-- start: PAGE TITLE -->
    <section id="page-title">
      <div class="row">
        <div class="col-sm-8">
          <h1 class="mainTitle">Admin Detail</h1>
          <span class="mainDescription">Halaman untuk melihat detail admin</span>
        </div>
        <ol class="breadcrumb">
          <li>
            <span>Admin View</span>
          </li>
          <li class="active">
            <span>View Admin</span>
          </li>
        </ol>
      </div>
    </section>
    <!-- end: PAGE TITLE -->
    <!-- start: BASIC EXAMPLE -->
    <div class="container-fluid container-fullw bg-white">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-lg-8 col-md-12">
              <div class="panel panel-white">
                <div class="panel-heading">
                  <h5 class="panel-title">Detail Admin</h5>
                </div>
                <div class="panel-body">
                  <table class="table">
                    <tbody>
                      <tr>
                        <td>Name</td>
                        <td><%= @admin.name %></td>
                      </tr>
                      <tr>
                        <td>Email</td>
                        <td><%= @admin.email %></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
          <div class="col-md-12 space20">
            <a href="/admins/<%= params[:id] %>/edit" class="btn btn-warning">
              Edit <i class="fa fa-edit"></i>
            </a>                
            <a href="/admins" class="btn btn-info">
              Back <i class="fa fa-reply"></i>
            </a>
          </div>
      </div>
    </div>
    <!-- end: BASIC EXAMPLE -->
  </div>

  <%= content_for :css do %>
    <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
    <link href="/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/DataTables/css/DT_bootstrap.css" rel="stylesheet" media="screen">
    <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
  <% end %>

  <%= content_for :js do %>
    <script src="/vendor/select2/select2.min.js"></script>
    <script src="/vendor/DataTables/jquery.dataTables.min.js"></script>
    <!-- start: JavaScript Event Handlers for this page -->
    <script src="/assets/js/table-data.js"></script>
    <script>
      jQuery(document).ready(function() {
        Main.init();
        TableData.init();
      });
    </script>
    <!-- end: JavaScript Event Handlers for this page -->
  <% end %>
  