config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  #devise_for :users

  root 'homes#index'

  resources :homes
  resources :admins
  resources	:barcodes
  resources :user_groups
  resources :warehouse_statuses
  resources :warehouses do
    resources :warehouse_bins
  end
  
  resources :product_types  
  resources :users
  resources :delivery_orders
  resources :products

end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
	has_many :user
	belongs_to :warehouse_status
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  before_filter :authenticate_admin!
  before_action :set_user_group, only: [:show, :edit, :update, :destroy]

  layout "admin"
  
  # GET /user_groups
  # GET /user_groups.json
  def index
    @user_groups = UserGroup.all
  end

  # GET /user_groups/1
  # GET /user_groups/1.json
  def show
  end

  # GET /user_groups/new
  def new
    @user_group = UserGroup.new 
    @warehouse_statuses = WarehouseStatus.all
  end

  # GET /user_groups/1/edit
  def edit
     @warehouse_statuses = WarehouseStatus.all
  end

  # POST /user_groups
  # POST /user_groups.json
  def create
    @user_group = UserGroup.new(user_group_params)

    respond_to do |format|
      if @user_group.save
        format.html { redirect_to [@user_group], notice: 'UserGroup was successfully created.' }
        format.json { render :show, status: :created, location: @user_group }
      else
        format.html { render :new }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_groups/1
  # PATCH/PUT /user_groups/1.json
  def update
    respond_to do |format|
      if @user_group.update(user_group_params)
        format.html { redirect_to [@user_group], notice: 'UserGroup was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_group }
      else
        format.html { render :edit }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_groups/1
  # DELETE /user_groups/1.json
  def destroy
    @user_group.destroy
    respond_to do |format|
     format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_group
      @user_group = UserGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_group_params
      params.require(:user_group).permit(:name, :description, :warehouse_status_id)
    end

end

app/helpers/admin/user_group_helper.rb
module Admin::UserGroupHelper
end

app/views/user_groups/_form.html.erb
<%= form_for(@user_group, html: {class: "form-horizontal"}) do |f| %>
  <% if @user_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_group.errors.count, "error") %> prohibited this user_group from being saved:</h2>

      <ul>
      <% @user_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if params[:action] == "new" %>
      <%= f.hidden_field :created_by, :value => current_admin.id %>
    <% else %>
      <%= f.hidden_field :updated_by, :value => current_admin.id %>
    <% end %>

  <div class="form-group">
    <label class="col-sm-3 control-label">
      Name
    </label>
    <div class="col-sm-7">
      <%= f.text_field :name, class: 'form-control', placeholder: 'Enter Name ..' %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">
      Description
    </label>
    <div class="col-sm-7">
      <%= f.text_field :description, class: 'form-control', placeholder: 'Enter Description ..' %>
    </div>
  </div>  
  <div class="form-group">
    <label class="col-sm-3 control-label">
      Warehouse Status
    </label>
    <div class="col-sm-7">
             <%= f.collection_select :warehouse_status_id , @warehouse_statuses.order(:name),:id,:name, {:include_blank => "-- Select Warahouse Status --" }, :class => "form-control js-example-basic-single js-states"  %>
        </div>
  </div>
  
  <button type="submit" class="btn btn-o btn-primary">
    Submit
  </button>
<% end %>

<%= content_for :css do %>
  
    <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
    <link href="/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/bootstrap-datepicker/bootstrap-datepicker3.standalone.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/bootstrap-timepicker/bootstrap-timepicker.min.css" rel="stylesheet" media="screen">
    <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
<% end %>

<%= content_for :js do %>
    
    <!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
    <script src="/vendor/ckeditor/ckeditor.js"></script>
    <script src="/vendor/ckeditor/adapters/jquery.js"></script>
    <script src="/vendor/jquery-validation/jquery.validate.min.js"></script>

    <script src="/vendor/maskedinput/jquery.maskedinput.min.js"></script>
    <script src="/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js"></script>
    <script src="/vendor/autosize/autosize.min.js"></script>
    <script src="/vendor/selectFx/classie.js"></script>
    <script src="/vendor/selectFx/selectFx.js"></script>
    <script src="/vendor/select2/select2.min.js"></script>
    <script src="/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <script src="/vendor/bootstrap-timepicker/bootstrap-timepicker.min.js"></script>
    <!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
  
    <!-- start: JavaScript Event Handlers for this page -->
    <script src="/assets/js/form-validation.js"></script>
    <script src="/assets/js/form-elements.js"></script>
    <script>
      jQuery(document).ready(function() {
        Main.init();
        FormValidator.init();
        FormElements.init();
      });
    </script>
<% end %>

app/views/user_groups/edit.html.erb
					<div class="wrap-content container" id="container">
						<!-- start: PAGE TITLE -->
						<section id="page-title">
							<div class="row">
								<div class="col-sm-8">
									<h1 class="mainTitle">Form Ubah User Group</h1>
									<span class="mainDescription">Form untuk ubah data User Group</span>
								</div>
								<ol class="breadcrumb">
									<li>
										<span>User Group Forms</span>
									</li>
									<li class="active">
										<span>Form User Group</span>
									</li>
								</ol>
							</div>
						</section>
						<!-- end: PAGE TITLE -->
						<!-- start: BASIC EXAMPLE -->
						<div class="container-fluid container-fullw bg-white">
							<div class="row">
								<div class="col-md-12">
									<div class="row">
										<div class="col-lg-8 col-md-12">
											<div class="panel panel-white">
												<div class="panel-heading">
													<h5 class="panel-title">Form Ubah</h5>
												</div>
												<div class="panel-body">
													<%= render "form" %>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>

							<div class="row">
			                    <div class="col-md-12 space20">
								<a href="/user_groups/<%= params[:id] %>" class="btn btn-green">
									Show <i class="fa fa-search-plus"></i>
								</a>
								<a href="/user_groups" class="btn btn-info">
									Back <i class="fa fa-reply"></i>
								</a>
			                    </div>
		                  	</div>
						</div>
						<!-- end: BASIC EXAMPLE -->
					</div>

app/views/user_groups/index.html.erb
          <div class="wrap-content container" id="container">
            <!-- start: PAGE TITLE -->
            <section id="page-title">
              <div class="row">
                <div class="col-sm-8">
                  <h1 class="mainTitle">USER GROUP LIST</h1>
                  <span class="mainDescription">Halaman untuk menampilkan daftar user group</span>
                </div>
                <ol class="breadcrumb">
                  <li>
                    <span>Dashboard</span>
                  </li>
                  <li class="active">
                    <span>User Group List</span>
                  </li>
                </ol>
              </div>
            </section>
            <p id="notice"><%= notice %></p>
            <!-- end: PAGE TITLE -->
            <!-- start: DYNAMIC TABLE -->
            <div class="container-fluid container-fullw">
              <div class="row">
                <div class="col-md-12">
                  <h5 class="over-title margin-bottom-15">List of <span class="text-bold">User Group</span></h5>
                  <div class="row">
                    <div class="col-md-12 space20">
                      <a href="/user_groups/new" class="btn btn-green">
                        Add New <i class="fa fa-plus"></i>
                      </a>
                    </div>
                  </div>
               <!--     <div class="row">
                    <div class="col-md-12 space20">

                      <a href="/user_excels/new" class="btn btn-blue">
                        Import <i class="fa fa-plus"></i>
                      </a>
                      
                    </div>
                  </div> -->
                  <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover table-full-width dataTable no-footer" id="sample_1">
                      <thead>
                        <tr>
                          <th>Name</th>
                          <th>Description</th>
                          <th>Warehouse Status</th>
                          <th>Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @user_groups.each do |user_group| %>
                          <tr>
                            <td><%= link_to user_group.name, user_group_path(user_group) %></td>
                            <td><%= user_group.description %></td>
                            <td><%= user_group.warehouse_status.name %></td>
                            <td>
                              <%= link_to edit_user_group_path(user_group) do %>
                                <i class="fa fa-edit"></i>
                              <% end %>

                              <%= link_to user_group_path(user_group), method: :delete, data: {confirm: "are you sure?"} do %>
                                <i class="fa fa-trash"></i>
                              <% end %>
                            </td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <%= content_for :css do %>
            <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
            <link href="/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
            <link href="/vendor/DataTables/css/DT_bootstrap.css" rel="stylesheet" media="screen">
            <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
          <% end %>

          <%= content_for :js do %>
            <script src="/vendor/select2/select2.min.js"></script>
            <script src="/vendor/DataTables/jquery.dataTables.min.js"></script>
            <!-- start: JavaScript Event Handlers for this page -->
            <script src="/assets/js/table-data.js"></script>
            <script>
              jQuery(document).ready(function() {
                Main.init();
                TableData.init();
              });
            </script>
            <!-- end: JavaScript Event Handlers for this page -->
          <% end %>

app/views/user_groups/new.html.erb
<div class="wrap-content container" id="container">
	<!-- start: PAGE TITLE -->
	<section id="page-title">
<div class="row">
<div class="col-sm-8">
	<h1 class="mainTitle">Form Tambah User Group</h1>
	<span class="mainDescription">Form untuk menambah data User Group yang baru</span>
</div>
<ol class="breadcrumb">
	<li>
		<span>User Group Forms</span>
	</li>
	<li class="active">
		<span>Form User Group</span>
	</li>
</ol>
</div>
</section>
<!-- end: PAGE TITLE -->
<!-- start: BASIC EXAMPLE -->
<div class="container-fluid container-fullw bg-white">
<div class="row">
<div class="col-md-12">
	<div class="row">
		<div class="col-lg-8 col-md-12">
			<div class="panel panel-white">
				<div class="panel-heading">
					<h5 class="panel-title">Form Tambah</h5>
				</div>
				<div class="panel-body">
					<%= render "form" %>
				</div>
			</div>
		</div>
	</div>
</div>
</div>

<div class="row">
<a href="/user_groups" class="btn btn-info">
  Back <i class="fa fa-reply"></i>
</a>
</div>
</div>
<!-- end: BASIC EXAMPLE -->
</div>

app/views/user_groups/show.html.erb
  <div class="wrap-content container" id="container">
    <!-- start: PAGE TITLE -->
    <section id="page-title">
      <div class="row">
        <div class="col-sm-8">
          <h1 class="mainTitle">User Group Detail</h1>
          <span class="mainDescription">Halaman untuk melihat detail user group</span>
        </div>
        <ol class="breadcrumb">
          <li>
            <span>User Group View</span>
          </li>
          <li class="active">
            <span>View User Group</span>
          </li>
        </ol>
      </div>
    </section>
    <!-- end: PAGE TITLE -->
    <!-- start: BASIC EXAMPLE -->
    <div class="container-fluid container-fullw bg-white">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-lg-8 col-md-12">
              <div class="panel panel-white">
                <div class="panel-heading">
                  <h5 class="panel-title">Detail User Group</h5>
                </div>
                <div class="panel-body">
                  <table class="table">
                    <tbody>
                      <tr>
                        <td>Name</td>
                        <td><%= @user_group.name %></td>
                      </tr>
                      <tr>
                        <td>Description</td>
                        <td><%= @user_group.description %></td>
                      </tr>
                      <tr>
                        <td>Warehouse Status</td>
                        <td><%= @user_group.warehouse_status.name %></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
          <div class="col-md-12 space20">
            <a href="/user_groups/<%= params[:id] %>/edit" class="btn btn-warning">
              Edit <i class="fa fa-edit"></i>
            </a>                
            <a href="/user_groups" class="btn btn-info">
              Back <i class="fa fa-reply"></i>
            </a>
          </div>
      </div>
    </div>
    <!-- end: BASIC EXAMPLE -->
  </div>

  <%= content_for :css do %>
    <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
    <link href="/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/DataTables/css/DT_bootstrap.css" rel="stylesheet" media="screen">
    <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
  <% end %>

  <%= content_for :js do %>
    <script src="/vendor/select2/select2.min.js"></script>
    <script src="/vendor/DataTables/jquery.dataTables.min.js"></script>
    <!-- start: JavaScript Event Handlers for this page -->
    <script src="/assets/js/table-data.js"></script>
    <script>
      jQuery(document).ready(function() {
        Main.init();
        TableData.init();
      });
    </script>
    <!-- end: JavaScript Event Handlers for this page -->
  <% end %>
  