config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  #devise_for :users

  root 'homes#index'

  resources :homes
  resources :admins
  resources	:barcodes
  resources :user_groups
  resources :warehouse_statuses
  resources :warehouses do
    resources :warehouse_bins
  end
  
  resources :product_types  
  resources :users
  resources :delivery_orders
  resources :products

end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
before_filter :authenticate_admin!
  before_action :set_warehouse, only: [:show, :edit, :update, :destroy]
  
  layout "admin"
  # GET /warehouses
  # GET /warehouses.json
  def index
    @warehouses = Warehouse.all
  end

  # GET /warehouses/1
  # GET /warehouses/1.json
  def show
    @warehouse_bin = @warehouse.warehouse_bins
    #render json: @warehouse_bin
  end

  # GET /warehouses/new
  def new
    @warehouse = Warehouse.new
  end

  # GET /warehouses/1/edit
  def edit
  end

  # POST /warehouses
  # POST /warehouses.json
  def create
    @warehouse = Warehouse.new(warehouse_params)

    respond_to do |format|
      if @warehouse.save
        format.html { redirect_to [@warehouse], notice: 'Warehouse was successfully created.' }
        format.json { render :show, status: :created, location: @warehouse }
      else
        format.html { render :new }
        format.json { render json: @warehouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /warehouses/1
  # PATCH/PUT /warehouses/1.json
  def update
    respond_to do |format|
      if @warehouse.update(warehouse_params)
        format.html { redirect_to [@warehouse], notice: 'Warehouse was successfully updated.' }
        format.json { render :show, status: :ok, location: @warehouse }
      else
        format.html { render :edit }
        format.json { render json: @warehouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /warehouses/1
  # DELETE /warehouses/1.json
  def destroy
    @warehouse.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Warehouse was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_warehouse
      @warehouse = Warehouse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def warehouse_params
      params.require(:warehouse).permit(:name, :description, :lat, :long, :address, :state_id, :district_id, :sub_district_id)
    end
end

app/helpers/admin/warehouses_helper.rb
module Admin::WarehousesHelper
end

app/views/warehouses/_form.html.erb
<%= form_for(@warehouse, html: {class: "form-horizontal"}) do |f| %>
  <% if @warehouse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@warehouse.errors.count, "error") %> prohibited this warehouse from being saved:</h2>

      <ul>
      <% @warehouse.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if params[:action] == "new" %>
      <%= f.hidden_field :created_by, :value => current_admin.id %>
    <% else %>
      <%= f.hidden_field :updated_by, :value => current_admin.id %>
    <% end %>

  <div class="form-group">
    <label class="col-sm-3 control-label">
      Name
    </label>
    <div class="col-sm-7">
      <%= f.text_field :name, class: 'form-control', placeholder: 'Enter name ..' %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">
      Description
    </label>
    <div class="col-sm-7">
      <%= f.text_field :description, class: 'form-control', placeholder: 'Enter description ..' %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">
      Lat
    </label>
    <div class="col-sm-7">
      <%= f.text_field :lat, class: 'form-control', placeholder: 'Enter lat ..' %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">
      Long
    </label>
    <div class="col-sm-7">
      <%= f.text_field :long, class: 'form-control', placeholder: 'Enter long ..' %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">
      Address
    </label>
    <div class="col-sm-7">
      <%= f.text_field :address, class: 'form-control', placeholder: 'Enter address ..' %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">
      State ID
    </label>
    <div class="col-sm-7">
      <%= f.text_field :state_id, class: 'form-control', placeholder: 'Enter state id ..' %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">
      District ID
    </label>
    <div class="col-sm-7">
      <%= f.text_field :district_id, class: 'form-control', placeholder: 'Enter district id ..' %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">
      Sub District ID
    </label>
    <div class="col-sm-7">
      <%= f.text_field :sub_district_id, class: 'form-control', placeholder: 'Enter sub district id ..' %>
    </div>
  </div>
  <button type="submit" class="btn btn-o btn-primary">
    Submit
  </button>
<% end %>

<%= content_for :css do %>
  
    <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
    <link href="/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/bootstrap-datepicker/bootstrap-datepicker3.standalone.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/bootstrap-timepicker/bootstrap-timepicker.min.css" rel="stylesheet" media="screen">
    <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
<% end %>

<%= content_for :js do %>
    
    <!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
    <script src="/vendor/ckeditor/ckeditor.js"></script>
    <script src="/vendor/ckeditor/adapters/jquery.js"></script>
    <script src="/vendor/jquery-validation/jquery.validate.min.js"></script>

    <script src="/vendor/maskedinput/jquery.maskedinput.min.js"></script>
    <script src="/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js"></script>
    <script src="/vendor/autosize/autosize.min.js"></script>
    <script src="/vendor/selectFx/classie.js"></script>
    <script src="/vendor/selectFx/selectFx.js"></script>
    <script src="/vendor/select2/select2.min.js"></script>
    <script src="/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <script src="/vendor/bootstrap-timepicker/bootstrap-timepicker.min.js"></script>
    <!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
  
    <!-- start: JavaScript Event Handlers for this page -->
    <script src="/assets/js/form-validation.js"></script>
    <script src="/assets/js/form-elements.js"></script>
    <script>
      jQuery(document).ready(function() {
        Main.init();
        FormValidator.init();
        FormElements.init();
      });
    </script>
<% end %>

app/views/warehouses/edit.html.erb
					<div class="wrap-content container" id="container">
						<!-- start: PAGE TITLE -->
						<section id="page-title">
							<div class="row">
								<div class="col-sm-8">
									<h1 class="mainTitle">Form Ubah Warehouse</h1>
									<span class="mainDescription">Form untuk ubah data Warehouse</span>
								</div>
								<ol class="breadcrumb">
									<li>
										<span>Warehouse Forms</span>
									</li>
									<li class="active">
										<span>Form Warehouse</span>
									</li>
								</ol>
							</div>
						</section>
						<!-- end: PAGE TITLE -->
						<!-- start: BASIC EXAMPLE -->
						<div class="container-fluid container-fullw bg-white">
							<div class="row">
								<div class="col-md-12">
									<div class="row">
										<div class="col-lg-8 col-md-12">
											<div class="panel panel-white">
												<div class="panel-heading">
													<h5 class="panel-title">Form Ubah</h5>
												</div>
												<div class="panel-body">
													<%= render "form" %>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>

							<div class="row">
			                    <div class="col-md-12 space20">
								<a href="/admins/<%= params[:id] %>" class="btn btn-green">
									Show <i class="fa fa-search-plus"></i>
								</a>
								<a href="/warehouses" class="btn btn-info">
									Back <i class="fa fa-reply"></i>
								</a>
			                    </div>
		                  	</div>
						</div>
						<!-- end: BASIC EXAMPLE -->
					</div>

app/views/warehouses/index.html.erb
          <div class="wrap-content container" id="container">
            <!-- start: PAGE TITLE -->
            <section id="page-title">
              <div class="row">
                <div class="col-sm-8">
                  <h1 class="mainTitle">WAREHOUSE LIST</h1>
                  <span class="mainDescription">Halaman untuk menampilkan daftar warehouse</span>
                </div>
                <ol class="breadcrumb">
                  <li>
                    <span>Dashboard</span>
                  </li>
                  <li class="active">
                    <span>Warehouse List</span>
                  </li>
                </ol>
              </div>
            </section>
            <p id="notice"><%= notice %></p>
            <!-- end: PAGE TITLE -->
            <!-- start: DYNAMIC TABLE -->
            <div class="container-fluid container-fullw">
              <div class="row">
                <div class="col-md-12">
                  <h5 class="over-title margin-bottom-15">List of <span class="text-bold">Warehouse</span></h5>
                  <div class="row">
                    <div class="col-md-12 space20">
                      <a href="/warehouses/new" class="btn btn-green">
                        Add New <i class="fa fa-plus"></i>
                      </a>
                    </div>
                  </div>
               <!--     <div class="row">
                    <div class="col-md-12 space20">

                      <a href="/user_excels/new" class="btn btn-blue">
                        Import <i class="fa fa-plus"></i>
                      </a>
                      
                    </div>
                  </div> -->
                  <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover table-full-width dataTable no-footer" id="sample_1">
                      <thead>
                        <tr>
                          <th>Name</th>
                          <th>Description</th>
                          <th>Lat</th>
                          <th>Long</th>
                          <th>Address</th>
                          <th>State ID</th>
                          <th>District ID</th>
                          <th>Sub District ID</th>   
                          <th>Action</th>
                        </tr>
                      </thead>
                       <tbody>
                        <% @warehouses.each do |warehouse| %>
                          <tr>
                            <td><%= link_to warehouse.name, warehouse_path(warehouse) %></td>
                            <td><%= warehouse.description %></td>
                            <td><%= warehouse.lat %></td>
                            <td><%= warehouse.long %></td>
                            <td><%= warehouse.address %></td>
                            <td><%= warehouse.state_id %></td>
                            <td><%= warehouse.district_id %></td>
                            <td><%= warehouse.sub_district_id %></td>
                            <td>
                              <%= link_to edit_warehouse_path(warehouse) do %>
                                <i class="fa fa-edit"></i>
                              <% end %>

                              <%= link_to warehouse_path(warehouse), method: :delete, data: {confirm: "are you sure?"} do %>
                                <i class="fa fa-trash"></i>
                              <% end %>
                            </td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <%= content_for :css do %>
            <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
            <link href="/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
            <link href="/vendor/DataTables/css/DT_bootstrap.css" rel="stylesheet" media="screen">
            <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
          <% end %>

          <%= content_for :js do %>
            <script src="/vendor/select2/select2.min.js"></script>
            <script src="/vendor/DataTables/jquery.dataTables.min.js"></script>
            <!-- start: JavaScript Event Handlers for this page -->
            <script src="/assets/js/table-data.js"></script>
            <script>
              jQuery(document).ready(function() {
                Main.init();
                TableData.init();
              });
            </script>
            <!-- end: JavaScript Event Handlers for this page -->
          <% end %>

app/views/warehouses/new.html.erb
<div class="wrap-content container" id="container">
	<!-- start: PAGE TITLE -->
	<section id="page-title">
<div class="row">
<div class="col-sm-8">
	<h1 class="mainTitle">Form Tambah Warehouse</h1>
	<span class="mainDescription">Form untuk menambah data Warehouse yang baru</span>
</div>
<ol class="breadcrumb">
	<li>
		<span>Warehouse Forms</span>
	</li>
	<li class="active">
		<span>Form Warehouse</span>
	</li>
</ol>
</div>
</section>
<!-- end: PAGE TITLE -->
<!-- start: BASIC EXAMPLE -->
<div class="container-fluid container-fullw bg-white">
<div class="row">
<div class="col-md-12">
	<div class="row">
		<div class="col-lg-8 col-md-12">
			<div class="panel panel-white">
				<div class="panel-heading">
					<h5 class="panel-title">Form Tambah</h5>
				</div>
				<div class="panel-body">
					<%= render "form" %>
				</div>
			</div>
		</div>
	</div>
</div>
</div>

<div class="row">
<a href="/warehouses" class="btn btn-info">
  Back <i class="fa fa-reply"></i>
</a>
</div>
</div>
<!-- end: BASIC EXAMPLE -->
</div>

app/views/warehouses/show.html.erb
  <div class="wrap-content container" id="container">
    <!-- start: PAGE TITLE -->
    <section id="page-title">
      <div class="row">
        <div class="col-sm-8">
          <h1 class="mainTitle">Warehouse Detail</h1>
          <span class="mainDescription">Halaman untuk melihat detail warehouse</span>
        </div>
        <ol class="breadcrumb">
          <li>
            <span>Warehouse View</span>
          </li>
          <li class="active">
            <span>View Warehouse</span>
          </li>
        </ol>
      </div>
    </section>
    <!-- end: PAGE TITLE -->
    <!-- start: BASIC EXAMPLE -->
    <div class="container-fluid container-fullw bg-white">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-lg-8 col-md-12">
              <div class="panel panel-white">
                <div class="panel-heading">
                  <h5 class="panel-title">Detail Warehouse</h5>
                </div>
                <div class="panel-body">
                  <table class="table">
                    <tbody>
                      <tr>
                        <td>Name</td>
                        <td><%= @warehouse.name %></td>
                      </tr>
                      <tr>
                        <td>Description</td>
                        <td><%= @warehouse.description %></td>
                      </tr>
                      <tr>
                        <td>Lat</td>
                        <td><%= @warehouse.lat %></td>
                      </tr>
                      <tr>
                        <td>Long</td>
                        <td><%= @warehouse.long %></td>
                      </tr>
                      <tr>
                        <td>Address</td>
                        <td><%= @warehouse.address %></td>
                      </tr>
                      <tr>
                        <td>State ID</td>
                        <td><%= @warehouse.state_id %></td>
                      </tr>
                      <tr>
                        <td>District ID</td>
                        <td><%= @warehouse.district_id %></td>
                      </tr>
                      <tr>
                        <td>Sub District ID</td>
                        <td><%= @warehouse.sub_district_id %></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
          <div class="col-md-12 space20">
            <a href="/warehouses/<%= params[:id] %>/edit" class="btn btn-warning">
              Edit <i class="fa fa-edit"></i>
            </a>                
            <a href="/warehouses" class="btn btn-info">
              Back <i class="fa fa-reply"></i>
            </a>
          </div>
      </div>
    </div>
    <!-- end: BASIC EXAMPLE -->
  </div>

<div class="wrap-content container" id="container">
  <!-- start: PAGE TITLE -->
  <section id="page-title">
    <div class="row">
      <div class="col-sm-8">
        <h1 class="mainTitle">WAREHOUSE BIN LIST</h1>
        <span class="mainDescription">Halaman untuk menampilkan daftar warehouse bin</span>
      </div>
      <ol class="breadcrumb">
        <li>
          <span>Dashboard</span>
        </li>
        <li class="active">
          <span>Warehouse Bin List</span>
        </li>
      </ol>
    </div>
  </section>
  <p id="notice"><%= notice %></p>
  <!-- end: PAGE TITLE -->
  <!-- start: DYNAMIC TABLE -->
  <div class="container-fluid container-fullw">
    <div class="row">
      <div class="col-md-12">
        <h5 class="over-title margin-bottom-15">List of <span class="text-bold">Warehouse Bin</span></h5>
        <div class="row">
          <div class="col-md-12 space20">
            <a href="/warehouses/<%= @warehouse.id %>/warehouse_bins/new" class="btn btn-green">
              Add New <ID class="fa fa-plus"></i>
            </a>
          </div>
        </div>
        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover table-full-width dataTable no-footer" id="sample_1">
            <thead>
              <tr>
                <th>Warehouse</th>
                <th>Bin Number</th>                  
                <th>Action</th>
              </tr>
            </thead>
             <tbody>
              <% @warehouse_bin.each do |warehouse_bin| %>
                <tr>
                  <td><%= link_to warehouse_bin.warehouse.name, warehouse_warehouse_bin_path(@warehouse.id,warehouse_bin) %></td>
                  <td><%= warehouse_bin.bin_number %></td>
                  <td>
                    <%= link_to edit_warehouse_warehouse_bin_path(@warehouse.id, warehouse_bin) do %>
                      <i class="fa fa-edit"></i>
                    <% end %>

                    <%= link_to warehouse_warehouse_bin_path(@warehouse.id, warehouse_bin), method: :delete, data: {confirm: "are you sure?"} do %>
                      <i class="fa fa-trash"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>


  <%= content_for :css do %>
    <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
    <link href="/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/DataTables/css/DT_bootstrap.css" rel="stylesheet" media="screen">
    <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
  <% end %>

  <%= content_for :js do %>
    <script src="/vendor/select2/select2.min.js"></script>
    <script src="/vendor/DataTables/jquery.dataTables.min.js"></script>
    <!-- start: JavaScript Event Handlers for this page -->
    <script src="/assets/js/table-data.js"></script>
    <script>
      jQuery(document).ready(function() {
        Main.init();
        TableData.init();
      });
    </script>
    <!-- end: JavaScript Event Handlers for this page -->
  <% end %>
  